use_frameworks!

platform :ios, '9.0'

target 'PixleeTestCocoapods_Example' do
  pod 'PixleeTestCocoapods', :path => '../'

  target 'PixleeTestCocoapods_Tests' do
    inherit! :search_paths

    
  end
end
